name       : ruby-bcrypt_pbkdf
version    : 1.0.0
release    : 2
source     :
    - https://rubygems.org/downloads/bcrypt_pbkdf-1.0.0.gem : 1b86abaca5f4b0e9626b3218ba8f680863bfb3ea2316e1cf647be3c346984432
license    : MIT
component  : programming.ruby
summary    : RubyGem - bcrypt_pbkdf
description: |
    bcrypt_pdkfd is a ruby gem implementing bcrypt_pdkfd from OpenBSD. This is currently used by net-ssh to read password encrypted Ed25519 keys.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
